import streamlit as st
import pickle
import numpy as np
import pandas as pd

model = pickle.load(open("LoanDefaulter_LightGBM.pkl","rb"))

features = ['ORGANIZATION_TYPE', 'EXT_SOURCE_3', 'EXT_SOURCE_2', 'YEARS_ID_PUBLISH', 'YEARS_EMPLOYED', 'YEARS_REGISTRATION', 'YEARS_BIRTH', 'AMT_ANNUITY', 'SK_ID_CURR', 'REGION_POPULATION_RELATIVE', 'YEARS_LAST_PHONE_CHANGE', 'PREV_SELLERPLACE_AREA_MEAN', 'PREV_YEARS_DECISION_MEAN', 'AMT_CREDIT', 'PREV_HOUR_APPR_PROCESS_START_MEAN', 'PREV_YEARS_FIRST_DUE_MEAN', 'PREV_CNT_PAYMENT_MAX', 'AMT_INCOME_TOTAL', 'AMT_GOODS_PRICE', 'PREV_AMT_ANNUITY_MEAN', 'PREV_YEARS_LAST_DUE_1ST_VERSION_MEAN', 'PREV_AMT_ANNUITY_MEDIAN', 'PREV_SK_ID_PREV_COUNT', 'PREV_YEARS_TERMINATION_MEAN', 'PREV_AMT_CREDIT_MEDIAN', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'PREV_YEARS_LAST_DUE_MEAN', 'OCCUPATION_TYPE', 'PREV_AMT_APPLICATION_MEDIAN', 'PREV_PRODUCT_COMBINATION_LAMBDA', 'PREV_AMT_CREDIT_MEAN', 'CNT_FAM_MEMBERS', 'OBS_30_CNT_SOCIAL_CIRCLE', 'OWN_CAR_AGE', 'PREV_AMT_APPLICATION_MEAN', 'PREV_AMT_GOODS_PRICE_MEDIAN', 'HOUR_APPR_PROCESS_START', 'PREV_AMT_GOODS_PRICE_MEAN', 'PREV_YEARS_FIRST_DRAWING_MEAN', 'PREV_SK_ID_CURR_FIRST', 'OBS_60_CNT_SOCIAL_CIRCLE', 'PREV_NAME_GOODS_CATEGORY_LAMBDA', 'PREV_NFLAG_INSURED_ON_APPROVAL_MAX', 'WEEKDAY_APPR_PROCESS_START', 'PREV_WEEKDAY_APPR_PROCESS_START_LAMBDA']

st.title("Loan Defaulter Prediction App")

inputs = {}
for f in features:
    if f in ["ORGANIZATION_TYPE","OCCUPATION_TYPE","WEEKDAY_APPR_PROCESS_START"]:
        inputs[f] = st.text_input(f)
    else:
        inputs[f] = st.number_input(f, value=0.0)

if st.button("Predict"):
    df = pd.DataFrame([inputs])
    pred = model.predict(df)[0]
    st.write("Defaulter" if pred==1 else "Not a Defaulter")
